project:
  type: book

book:
  title: "Basic Ecological Concepts and Data in R"
  author: "Dr. Hank Stevens"
  date: "14 January 2026"
  google-analytics:
    tracking-id: "G-J0R6F7XN66"
  chapters:
    - index.qmd
    - 01-computer-setup.qmd
    - 01-trees_and_people.qmd
    - 02-global_temp_anomalies.qmd
    - 03-liana-phys.qmd
    - 04-extrapair_copulation.qmd
    - 06-DI-pop-growth.qmd
    - 07-structured-pop-growth_v2.qmd
    - 08-density-dep-pop-growth.qmd
    - 09-direct-interactions.qmd
    - 10-mutualisms.qmd
    - 11-predator-prey.qmd
    - 13-diversity.qmd
    - 20-ecosystem-intro.qmd
    - references.qmd

bibliography: myLibrary.bib

format:
  html:
    theme: default
    mainfont: serif
  # pdf:
  #   documentclass: scrreprt

editor: source


